name: tumor_detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py39hcbf5309_0
  - cffi=1.14.6=py39h0878f49_1
  - chardet=4.0.0=py39hcbf5309_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2021.3.0=haa95532_3372
  - jasper=2.0.14=h77af90b_2
  - jbig=2.1=h8d14728_2003
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - kaggle=1.5.12=py39hcbf5309_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - liblapacke=3.9.0=5_hd5c7e75_netlib
  - libopencv=4.5.3=py39h41a9e09_2
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.16.0=h7755175_0
  - libtiff=4.3.0=h0c97f57_1
  - libuv=1.40.0=he774522_0
  - libwebp-base=1.2.1=h8ffe710_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.2=h6d14046_1
  - numpy=1.20.3=py39ha4e8547_0
  - numpy-base=1.20.3=py39hc2deb75_0
  - olefile=0.46=pyhd3eb1b0_0
  - opencv=4.5.3=py39hcbf5309_2
  - openssl=1.1.1l=h8ffe710_0
  - pandas=1.3.3=py39h2e25243_0
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py38haa95532_0
  - py-opencv=4.5.3=py39h832f523_2
  - pycparser=2.20=pyh9f0ad1d_2
  - pydicom=2.2.2=pyh6c4a22f_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-slugify=5.0.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.8.1=py3.9_cuda10.1_cudnn7_0
  - pytz=2021.1=pyhd8ed1ab_0
  - qt=5.12.9=h5909a2a_4
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scipy=1.7.1=py39hbe87c03_2
  - setuptools=58.0.4=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - text-unidecode=1.3=py_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h2bbff1b_0
  - torchvision=0.2.2=py_3
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - unidecode=1.3.2=pyhd8ed1ab_0
  - urllib3=1.24.3=py_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39haa95532_2
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.5.0=h6255e5f_0
prefix: C:\Users\ruslantau\miniconda3\envs\tumor_detection
